### ISSUE TITLE
RadlistView feature request - to be able to stop a reorder

### ISSUE THREAD

**Issue by sflament** [telerik/nativescript-ui-samples#100]
Hello,

I don't know if it's already possible.

I would like to stop an reorder attempt on some items in the list.
To check if the item is authorized or not to be moved, I think to throw a stop reorder action inside the ReorderStartEvent  function. I don't know how to abort the ongoing reorder.

Stéphane

**Comment by Natalia-Hristova** [comment]
Hello @sflament , 

I'll move this issue in our dedicated GitHub repository for NativeScript UI issues https://github.com/telerik/nativescript-ui-feedback/issues. All issues here will be moved (if they are still valid) and closed because this repository is only for examples.

If you have any feedback, issues or feature requests please log them in [nativescript-ui-feedback](https://github.com/telerik/nativescript-ui-feedback) repository.

Thanks in advance!
