### ISSUE TITLE
RadListView: navigate between indexes with remote control or tab key press.

### ISSUE THREAD

**Issue by Premitium** [telerik/nativescript-ui-samples#105]
Is it possible navigate with an arrow control (remote) through items that are loaded in a RadListView?

The app currently has got images loaded in a RadListView and more images are loading on demand when the RadListView is scrolled down.

What I am trying to achieve is to enable the user to get focus on one item and be able to navigate with a remote with arrows (up, down, left and right) to its neighbours.

If someone has an idea it will be much appreciated.

**Comment by Ivshti** [comment]
I'd like to add that this is default behaviour on many android components - to be able to navigate through them with an arrow-based user interface. The use case is TV / set-top-boxes

**Comment by Natalia-Hristova** [comment]
Hello @Premitium and @Ivshti , 

I'll move this issue in our dedicated GitHub repository for NativeScript UI issues https://github.com/telerik/nativescript-ui-feedback/issues. All issues here will be moved (if they are still valid) and closed because this repository is only for examples.

If you have any feedback, issues or feature requests please log them in [nativescript-ui-feedback](https://github.com/telerik/nativescript-ui-feedback) repository.

Thank you in advance!
