### ISSUE TITLE
SideDrawer questions/issue

### ISSUE THREAD

**Issue by bradmartin** [telerik/nativescript-ui-samples#118]
What happened to the `showOverNavigation="true"` showing the side drawer on top of the android statusbar? This was almost there in a previous release (3 months ago), it seemed to just need some more calculation on the height of the drawer for different devices. Without it showing over the statusbar it just seems half baked. Am I missing something, is this in the plans to do or is this the final for `showOverNavigation`?

**Comment by ginev** [comment]
@bradmartin it's been changed. Take a look at the documentation here: http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/SideDrawer/getting-started#showing-radsidedrawer-over-the-navigation-baraction-bar

**Comment by bradmartin** [comment]
It's still not perfect on android. Anyway the android side drawer can use the drawer layout so it goes behind the status bar when opening? CCC @tjvantoll (theme project)

**Comment by bradmartin** [comment]
![screenshot_20160825-084035](https://cloud.githubusercontent.com/assets/6006148/18051329/5e3ab70a-6db9-11e6-8bdc-38b5a620acba.png) - correct android side drawer. 

![screenshot_20160825-084730](https://cloud.githubusercontent.com/assets/6006148/18051353/7bc43cc4-6db9-11e6-8037-411e9514851f.png)
 - current side drawer using drawer page on android

**Comment by skarlatov** [comment]
Hi Brad,

The problem is that our drawer is a child of the the Page it is declared in and it gets arranged by the page layout below the status bar. We can't stretch it so that it renders under it without some hacks which we tried with the public "showOverNavigation" property and it was broken on some API levels.

Also we can't use the standard DrawerLayout because it doesn't allow the drawer content to be under the main content which is required by several of our drawer transitions.

Finally, to put the standard DrawerLayout under the status bar the user needs to modify the app theme and also to use a flag on DrawerLayout called fitsSystemWindows which under the hood tells you to call view.setSystemUIVisibility() which is introduced in API Level 11 and we need to support 8. We are planning to finally raise the minimum supported api but haven't done so as of yet.

**Comment by bradmartin** [comment]
What's supporting API 8? NativeScript doesnt go back that far so is this just the telerik android controls that go back to 8?

**Comment by skarlatov** [comment]
Yes, the problem is in the native Android control. The native suite supports API 8.
