### ISSUE TITLE
Setting 'width' or 'height' to percentages in RadSideDrawer's 'tkDrawerContent' is not working

### ISSUE THREAD

**Issue by IvRRimum** [telerik/nativescript-ui-samples#132]
Hello i am using RadSideDrawer, the Top location. I am trying to make it fit in whole screen( or at least 90% height). Right now it's only like 30%( from top ).

**I am using {N} + angular2!**

Some current code:

```
<RadSideDrawer #drawer [drawerLocation]="drawerLocation">
```

```
this.drawerLocation = "Left";
```

```
 67   @ViewChild(RadSideDrawerComponent) public drawerComponent: RadSideDrawerComponent;
 68   private drawer: SideDrawerType;
```

```
 85   public openSearch() {
 86     this.isNavigation = false;
 87     this.drawerLocation = "Top";
 88     this.drawer.showDrawer();
 89   }
```

Thanks!

**Comment by VladimirAmiorkov** [comment]
Hi @IvRRimum ,

As mentioned by my response [here](https://github.com/telerik/nativescript-ui-samples/issues/53#issuecomment-251922949) setting the size of the RadSideDrawer's drawer content is achieved via the View's width/height properties. Those properties are settable to [percentages](https://docs.nativescript.org/ui/layouts#percentage-support) but have in mid that currently:

- Setting `width` to percentages works for `Top` and `Bottom` `drawerLocation`
- Setting `height` to percentages works for `Left` (default) and `Right` `drawerLocation`

I am going to edit the title to better illustrate the issue. Thank you for reporting this to us.

**Comment by Natalia-Hristova** [comment]
Hello @IvRRimum , 

I'll move this issue in our dedicated GitHub repository for NativeScript UI issues https://github.com/telerik/nativescript-ui-feedback/issues. All issues here will be moved (if they are still valid) and closed because this repository is only for examples.

If you have any feedback, issues or feature requests please log them in [nativescript-ui-feedback](https://github.com/telerik/nativescript-ui-feedback) repository.

Thank you in advance!
