### ISSUE TITLE
Feature: Expose a way to change the `RadLegendView` font-size,  font-color, backgroundColor

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-samples#134]
It will be great if the `RadLegendView` could support some more styling properties. For example:
-  font-size
- font-color
-  backgroundColor

**Comment by Natalia-Hristova** [comment]
Hello @tsonevn , 

I'll move this issue in our dedicated GitHub repository for NativeScript UI issues https://github.com/telerik/nativescript-ui-feedback/issues. All issues here will be moved (if they are still valid) and closed because this repository is only for examples.

If you have any feedback, issues or feature requests please log them in [nativescript-ui-feedback](https://github.com/telerik/nativescript-ui-feedback) repository.

Thank you in advance = )
