### ISSUE TITLE
[Bug, iOS] RadChart: the initial value is shown to the right of vertical axis (can't be styled)

### ISSUE THREAD

**Issue by NickIliev** [telerik/nativescript-ui-samples#139]
How to recreate: 

Create a basic chart with some initial data. Example app: [https://1drv.ms/u/s!Arrx7O3xsQXUhupzyloEBZ3G7zkUfg](https://1drv.ms/u/s!Arrx7O3xsQXUhupzyloEBZ3G7zkUfg)

Result: the value for 0 degrees is shown to the right of the vertical axis while we would
expect to be shown to the left (as all the other values)

Related to:  the first label of the axis is specific in native iOS and can not be controlled via NativeScript

**Comment by sophialazarova** [comment]
There are differences in the native behavior of the chart on iOS and Android. 
On iOS the first label is controlled by a separate property that is not taken into count when the labelLayoutMode is set to "Outer".
However, there is a workaround. The native property can be accessed through the ios object of the axis and aligned properly.

chart = page.getViewById("cartesianChart");
chart.series.getItem(0).verticalAxis.ios.style.labelStyle.firstLabelTextAlignment = TKChartAxisLabelAlignmentLeft;

**Comment by Natalia-Hristova** [comment]
Hello @NickIliev , 

All issues here will be moved (if they are still valid) and closed because this repository is only for examples.

If you have any feedback, issues or feature requests please log them in [nativescript-ui-feedback](https://github.com/telerik/nativescript-ui-feedback) repository.

Thank you in advance!
