### ISSUE TITLE
[RadListView] How to ged rid of these gray separator lines?

### ISSUE THREAD

**Issue by NordlingArt** [telerik/nativescript-ui-samples#147]
Using Staggered or Grid Layout on iOS, there are gray lines to either right or left (not sure why their position varies). See below:

![image](https://cloud.githubusercontent.com/assets/2098838/20596059/ecc2e6c4-b23c-11e6-8d6e-479cf8f36f71.png)

How can I get rid of them? They only seem to appear when the scrollDirection is set to "Vertical".

**UPDATE:** I went through all cells with this, where `radListView` is the instance:

```js
radListView.on("itemLoading", function(args) {
  var cell = args.view.ios.superview.superview;
  cell.layer.sublayers.objectAtIndex(1).hidden = true;
});
```

Making that second layer hidden removed the gray separayor line. Why is it even there in the first place?

**Comment by VladimirAmiorkov** [comment]
Hi @NordlingArt ,

I apologize for the late response.

We managed to reproduce the described behavior while having exactly `spanCount="4"` set. It looks like the native underlying layout component of the RadListView in iOS is showing a built-in separator.

Thank you for updating us with the workaround you have found, it is a valid solution. We will do our best to resolve this issue as soon as possible.

**Comment by Natalia-Hristova** [comment]
Hello @NordlingArt ,

I'll move this issue in our dedicated GitHub repository for NativeScript UI issues https://github.com/telerik/nativescript-ui-feedback/issues. All issues here will be moved (if they are still valid) and closed because this repository is only for examples. 

If you have any feedback, issues or feature requests please log them in [nativescript-ui-feedback](https://github.com/telerik/nativescript-ui-feedback/issues) repository.

Thanks for you understanding : )
