### ISSUE TITLE
RadListView ListViewGridLayout fitting images to screen

### ISSUE THREAD

**Issue by Sulman633** [telerik/nativescript-ui-samples#149]
Hi, this is probably a nooby question but I am still new to nativescript and telerik ui so please bare with me on this. What is the easiest way to fit to screen multiple images that are inside a radlistview which uses ListViewGridLayout(I have proper image sizes for each screen type saved in resources already). Basically I am trying to achieve something like this

http://docs.telerik.com/devtools/nativescript-ui/controls/NativeScript/ListView/Images/list-view-overview_3.png
That basically fits an size screen no matter the device.

What I have so far right now is this:
https://cloud.githubusercontent.com/assets/11000928/20693638/b6d0fa64-b5ad-11e6-8000-6dc638a3f661.png

As you can see the radlistview has white space at the bottom, I want to dynamically solve this height issue so that it would work for any device not just put in a static height value in css. 

Thanks for the help in advance!

**Comment by VladimirAmiorkov** [comment]
Hi @Sulman633 ,

Unfortunately there is not best solution for such requirement in a project. Looking at the screenshot that you have provided those images have an aspect ration that simply will not let them fill the entire space, since there are two rows (the grid layout) and the images aspect ration is such that their height is a lot smaller than their width in order for the image to be rendered in the correct ration and unless there a lot of images so that the vertical space filled with them you will not be able to achieve this.

Something that you can consider is:

- Why is this an issue, I mean if there are so few images with an aspect ration of such dimensions, physically there is not way they can fill the vertical space without either breaking the aspect ratio
- Is this a border case, I mean in your real scenario is it possible to have such few items in the RadListView. The listview control is designed to be used with heavy items loads so you shouldn't try to limit its items too much for performance

I will close this issue for now but feel free to post such questions in our official forums [here](http://www.telerik.com/forums/nativescript-ui).
