### ISSUE TITLE
License Info and GPL-Compatibility

### ISSUE THREAD

**Issue by Steviey** [telerik/nativescript-ui-samples#155]
Please follow the GitHub guidelines and add a license node for the sample code.
Open Source developers need this when ever they copy-paste a snipped (e.g. GPL-compatibility).
Commercial developers may need this too.

**Update:** Meanwhile I found the corresponding proprietary license for 'ui-for-nativescript-free' in the local node_modules folder and here http://www.telerik.com/purchase/license-agreement/ui-for-nativescript-free.

Currently the license for the royalty free product UI for NativeSctipt Free is NOT GPL-compatible.

Would it be possible to change the license to MIT or Apache 2 or GPL for the free product?

Then it would be possible to use listView and sideDrawer in GPL-licensed projects, which are the majority of open source projects. It would also increase the market coverage of NativeScript + Angular 2.

PS:
Currently GPL-compatible:
Angular
Cordova
Electron
Titanium
React Native (not OSI approved)

**Comment by nikolay-diyanov** [comment]
Hey Steviey,

Thank you for raising this question. Unfortunately, we can't make the license of the examples GPL-compatible. The reason behind this is the usage of some third party resources which we should protect by using our own commercial license. Labeling the whole samples repository as let's say MIT would potentially threaten the rights of the used third party resources. Other than that, the code used in the samples app can be reused. As to the Free version of UI for NativeScript, I understand your point generally and we would consider this. A question here if I may - would it be better for your open-source projects to just have a reference to the npm package of UI for NativeScript Free (https://www.npmjs.com/package/nativescript-telerik-ui) (which is permitted with the current license) rather than bringing the whole package with your open source project?

Best regards,
Nikolay

**Comment by Steviey** [comment]
@nikolay-diyanov 

GPL compliance can only be provided, if the whole package, which results in a mobile end product is compliant. In other words it must not include any tools for packaging, compiling, special IDE stuff etc., but the complete source code of the end-product would have to be GPL-compliant.

There is currently a lot of confusion in the open source community related to this issues and mobile.
React Native has comparable issues right now...
https://discuss.reactjs.org/t/legal-department-did-not-allow-use-of-react/3309/16

Best regards,
Steviey

**Comment by ginev** [comment]
This issue was moved to telerik/nativescript-ui-feedback#114
