### ISSUE TITLE
Flickerings because of unnecessary page reloads.

### ISSUE THREAD

**Issue by Steviey** [telerik/nativescript-ui-samples#156]
Could we expect a real SPA version of the sample app aka Router Outlet?
It would provide production ready, real live code snippets.

I'm referring to this effect...
https://github.com/tjvantoll/nativescript-template-drawer/issues/3
...which is currently present in this package too.

Thank you.

**Comment by VladimirAmiorkov** [comment]
Hi @Steviey ,

As the title and the text in the description are not exactly related I am wondering if I understand you correctly. Is there an issue or would you simply like to have an NativeScript + Angular application which is an SPA "template" that you can refer or use as a starting point when starting your projects. If this is the case we have in our planning such task to provide exactly this kind of "template".

We will do our best to provide such project for you to make use of as soon as possible.

**Comment by Steviey** [comment]
If we understand flickering as an issue and not as a feature, title and text are related.

Anyways, in your case it is a feature. Meanwhile I managed to avoid this by using "<router-outlet>" instead of "<page-router-outlet>" described here: https://docs.nativescript.org/core-concepts/angular-navigation. 

So actually this issue is solved. 

Your plan to provide a running boilerplate is great. Most of the samples I tested "Hello World" etc. did not run on my Win-environment.

**Comment by VladimirAmiorkov** [comment]
Hi @Steviey ,

If you are referring to those gifs and their "flicker":
![1](https://cloud.githubusercontent.com/assets/4989411/21904908/f62dc70e-d90d-11e6-9fb4-443748e1a7cf.gif)
![2](https://cloud.githubusercontent.com/assets/4989411/21904909/f633f53e-d90d-11e6-81d6-5a045ea60a6b.gif)

This is indeed the way a navigation in the page-router-outlet is achieved. Yes the "router-outlet" is the way to not have such behavior since that outlet rather than navigating to a new "page" it is actually loading content into the current Page.

**Comment by Steviey** [comment]
Yep.

**Comment by ginev** [comment]
This issue was moved to telerik/nativescript-ui-feedback#117
