### ISSUE TITLE
Pull-to-refresh feature is a bit clumsy in RadListView

### ISSUE THREAD

**Issue by NordlingArt** [telerik/nativescript-ui-samples#157]
**Platform:** iOS
**TNS:** 2.4.0

If I pull down so the loading indicator reveals, the RadListView will refresh and pull itself up while I haven't let go of my finger yet. The list should only refresh once I have let go of the finger. This kind of kills the user experience as it is refreshing before I even have a chance to regret my command whether to refresh or not.

Also if I scroll down to the bottom of a RadListView and pulls up as fast as I can so that the bouncing effect goes beyond the pull-to-refresh trigger, it also refreshes the list. I don't think that should happen as well because, again, it wasn't in my command to refresh the list.

**Comment by Daxito** [comment]
+1
Related to https://github.com/telerik/nativescript-ui-feedback/issues/15

**Comment by Natalia-Hristova** [comment]
Hello @NordlingArt , 

I'll move this issue and its reference in our dedicated GitHub repository for NativeScript UI issues https://github.com/telerik/nativescript-ui-feedback/issues. All issues here will be moved (if they are still valid) and closed because this repository is only for examples.

If you have any feedback, issues or feature requests please log them in [nativescript-ui-feedback](https://github.com/telerik/nativescript-ui-feedback) repository.

Thank you in advance!
