### ISSUE TITLE
Rad List View - Selection with Header, Select all, Total popup 1 times, Separator. 

### ISSUE THREAD

**Issue by Zengratul** [telerik/nativescript-ui-samples#160]
I have 4 problems with Telerik Rad List View which need your help. I tried on Android.

1- The highlight of selection shows mistake location if I set it with header.

2- May Rad List View have error with multi-tasking?! The layout is broken when I use multi-tasking.
![problem 2](https://cloud.githubusercontent.com/assets/7825869/22136440/339f9ac8-df07-11e6-9ba0-590edfceeac7.gif)

3- I use Toast from Android to show popup, but when I choose "select all" on top right corner, I show a countable. Can I get a total number of files immediately?!

4- I can not insert separator line. I try as below code in my Grid Layout but it's not working.
<StackLayout height="2" backgroundColor="black"></StackLayout>
![problem 4](https://cloud.githubusercontent.com/assets/7825869/22136448/3aae6dee-df07-11e6-928d-875218a3a681.gif)

This is my package, please check it.
[Rad List View.zip](https://github.com/telerik/nativescript-ui-samples/files/718458/Rad.List.View.zip)

**Comment by Natalia-Hristova** [comment]
Hello @Zengratul, 

I'll move this issue in our dedicated GitHub repository for NativeScript UI issues https://github.com/telerik/nativescript-ui-feedback/issues. All issues here will be moved (if they are still valid) and closed because this repository is only for examples.

If you have any feedback, issues or feature requests please log them in [nativescript-ui-feedback](https://github.com/telerik/nativescript-ui-feedback) repository.

Thanks for your understanding!
