### ISSUE TITLE
Calendar: Changing first day of the week

### ISSUE THREAD

**Issue by deneshr** [telerik/nativescript-ui-samples#166]
Is it possible to configure the first day of the week?
Currently this depends on the user's locale setting (Either Sunday or Monday).
But I have a requirement to force the users to have Monday as the first day of the week.

**Comment by Natalia-Hristova** [comment]
Hello @deneshr , 

I'll move this issue in our dedicated GitHub repository for NativeScript UI issues https://github.com/telerik/nativescript-ui-feedback/issues. All issues here will be moved (if they are still valid) and closed because this repository is only for examples.

If you have any feedback, issues or feature requests please log them in nativescript-ui-feedback repository.

Thanks for your understanding!
