### ISSUE TITLE
JS ERROR ReferenceError: Can't find variable: TKSideDrawerDelegate

### ISSUE THREAD

**Issue by soeyanmin** [telerik/nativescript-ui-samples#168]
Still having this issue even after applied suggested above in iOS but android is working fine.
JS ERROR ReferenceError: Can't find variable: TKSideDrawerDelegate.

Thanks for the help

**Comment by Natalia-Hristova** [comment]
Hello @soeyanmin , 

I'll move this issue in our dedicated GitHub repository for NativeScript UI issues https://github.com/telerik/nativescript-ui-feedback/issues. All issues here will be moved (if they are still valid) and closed because this repository is only for examples.

If you have any feedback, issues or feature requests please log them in [nativescript-ui-feedback](https://github.com/telerik/nativescript-ui-feedback) repository.

Thank you in advance!
