### ISSUE TITLE
RadDataForm: Unable to rebind Picker for PropertyEditor a second time

### ISSUE THREAD

**Issue by Daxito** [telerik/nativescript-ui-samples#175]
### Did you verify this is a real problem by searching 
Yes, but did not find anything related to this new control

### Tell us about the problem
For iOS only, android is fine, for some reason when I re-populate a valuesProvider a second time, the App crashes. 

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.2
- Cross-platform modules: 2.5.1
- Runtime(s): 2.5.0
- Plugin(s): nativescript-telerik-ui-pro

### Please tell us how to recreate the issue in as much detail as possible.
1. Please run the attached App using iOS.
2. The first time you open it the Picker is empty, tap the "Modify List"
3. 3 Items are added to the picker.
4. Tap a second time to the "Modify List" in order to add different list of items
5. The App crashes.
6. Do the same for Android, not crashing and it works as expected

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
See Attached 
[comboSample.zip](https://github.com/telerik/nativescript-ui-samples/files/815248/comboSample.zip)

**Comment by Natalia-Hristova** [comment]
Hello @Daxito ,

As I see you logged/moved this issue in our dedicated GitHub repository for NativeScript UI issues https://github.com/telerik/nativescript-ui-feedback/issues. Thanks! I only will copy your comment there to be sure not loosing it and will close this issue here. 

All issues in this repository will be moved (if they are still valid) and closed because this one is only for examples. So please keep using the other repository.

Thank you in advance!
