### ISSUE TITLE
RadListView crashing when pushing items too quickly one after another

### ISSUE THREAD

**Issue by NordlingArt** [telerik/nativescript-ui-samples#176]
**Platform:** iOS
**TNS:** 2.5.1

This fatal error appears quite frequently when pushing items one after another asynchronously:

`*** Assertion failure in -[TKCollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3600.6.21/UICollectionView.m:5634`

This means I cannot animate incoming items because I have to avoid this error by loading every items synchronously and THEN attach the items ObservableArray to the RadListView.

I have seen people getting this problem before, but recently the support for nativescript-telerik-ui has been near none-existent. Can this be fixed somehow?

Thanks in advance

**Comment by Natalia-Hristova** [comment]
Hello @NordlingArt , 

Thanks for moving this issue in our dedicated GitHub repository for NativeScript UI issues https://github.com/telerik/nativescript-ui-feedback/issues. I'll close this one because this repository is only for examples.

If you have any feedback, issues or feature requests please log them in [nativescript-ui-feedback](https://github.com/telerik/nativescript-ui-feedback) repository.

Thank you in advance!
