### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by alexrainman** [telerik/nativescript-ui-samples#29]
I think a good way to distribute this thing is to split it in components/plugins and sell them separately in the component store.

RadSideDrawer will be free? Let's move it to NativeScript core.

So, if i want yo use RadListView on one of my projects i just go and get it without the need of buying a license for the whole thing.

**Comment by NikolayVasilev** [comment]
Hello Alex, 

Thank you for the suggestion, it is always helpful to hear what the customer is actually expecting from a certain product. 

We are currently evaluating options to split the controls in separate plugins. Whether **RadSideDrawer** will be part of the **NativeScript default modules** or be a separate free plugin, you won't need to buy a license to use it.

As to buying separate control plugins, since we are on an early stage of the controls development, everything is still in a "beta" phase, and currently has no specified bundling and marketing strategy. Again, thank you for the feedback, it will be taken into consideration while discussing the possible paths for the **UI for NativeScript** suite. 

Regards, 
Nikolay Vasilev

**Comment by alexrainman** [comment]
Great! I am really excited about {N}. Thanks.
