### ISSUE TITLE
TypeError - ListViewDataSourceAdapter

### ISSUE THREAD

**Issue by bradmartin** [telerik/nativescript-ui-samples#31]
Upgraded a 1.3 {N} project to 1.4, then updated the telerik-ui. Which added in the listview, I followed the step by step guide on using the listview. I've added the compile statement to build.gradle (compile "com.android.support:recyclerview-v7:$suppotVer") and then when I launch the app this error is thrown from the compiled listview.js file in the app. I've even manually 'prepare' and 'build' the app to make sure the app is current. 

*app*/files/app/tns_modules/nativescript-telerik-ui/listview/listview.js(71:27) which refs the following: 
    
       })(com.telerik.widget.list.ListViewDataSourceAdapter);

**Comment by ginev** [comment]
Hello @bradmartin ,

Can you paste the complete stack trace here so that I can gain a better understanding of the case? This seems to be related to missing native Android types. Can you try removing the Android platform and re-adding it once again doing the same steps for Telerik UI and let me know if it resolves the problem for you?

Thanks!

**Comment by bradmartin** [comment]
Doing the platform remove/add android the second time around cleared up the issue.
