### ISSUE TITLE
Crash bug with listview on android if you scroll too fast

### ISSUE THREAD

**Issue by stonecourier** [telerik/nativescript-ui-samples#33]
If you scroll too fast with the new listview on android the program crashes on line 34 of listview.android.js. Cannot set bindingContext of undefined.     

    ListViewAdapter.prototype.onBindItemViewHolder = function (holder, entity) {
        holder.nsView.bindingContext = JSON.parse(entity);
    };

Occurs repeatedly on my galaxy note 4.

**Comment by ginev** [comment]
Hello @stonecourier,

This issue was known to us and we have upgraded the code to address it. To make sure it is the same case, can you please confirm which version of the plugin you are using and can you try updating to the latest one (using npmjs.org) and let us know if the crash persists?

Thanks!

**Comment by stonecourier** [comment]
Hi,

I was using 0.1. Installed 0.1.1 and it now seems to work ok.

Thanks

**Comment by ginev** [comment]
@stonecourier, I am closing this issue. 
Let us know in case of additional questions.
