### ISSUE TITLE
RadSideDrawer taking up all the available vertical space while not preventing user interaction

### ISSUE THREAD

**Issue by dragGH102** [telerik/nativescript-ui-samples#55]
I noticed the drawer's background takes up all the screen vertically (my sideDrawer uses position = top and transition = reverse)

The issue can be seen at the same project mentioned in issue https://github.com/telerik/nativescript-ui-samples/issues/52
(Here it is for your convenience: https://github.com/dragGH102/nativescript-sample-app-with-menu )

Specifically I see 2 issues here:
- when the drawer slides out from **top**, it makes sense to **cover only the area the drawer's content** (i.e. the menu) uses. This is a #feature which makes sense in my opinion and it's actually a requirement of a project I'm working on
  I make a quick try: apparently the drawer's content takes up only the needed space (just try to put a background to the StackLayout with id= menu-content in includes/menuContent) but the semi-transparent overlay takes up all the screen vertically
- **the user is still able to interact with elements** which are below drawer's content and under the overlaid area (i.e. the 2nd half of the screen to the bottom)

**Comment by ginev** [comment]
Hello @dragGH102 ,

If I understand you correctly, the behavior you are seeing as an issue is actually the one which we have implemented by design. We are following the behavioral guidelines coming from Android and iOS here. When a Drawer menu is shown, the content below it is not accessible until after the drawer menu is closed. The Fade Layer which is covering the whole main content area is also part of the spec - basically you are not supposed to be able to interact with the contents of the page while the drawer is opened.

Can you be a bit more specific about the design of your app and the scenario you would like to achieve?

Thanks!

**Comment by dragGH102** [comment]
> The Fade Layer which is covering the whole main content area is also part
> of the spec


@Deyan  Thank you for the clarification.

My app as a button in the header to open the menu. the menu is then close
with a button within the menu.
In the mockups provided by the designer (as far as I know it's because they
wanted a similar experience on iOS + Android) the menu (drawer) comes out
from the top, covering aobut half of the screen without overlaying effect
on the rest of the screen. The scenario is similar to the one in the sample
app provided.

However, while I think the overlaying effect could be ok (I didn't discuss
it yet) I noticed the area which is covered by the overlay but not from the
menu content itself it's "tappable" (e.g. if there is some image or button
with tap event on it). Do you think you can quickly reproduce it based on
the provided example?
Otherwise let me know and I'll try to do it


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Questa
e-mail è stata inviata da un computer privo di virus protetto da Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
