### ISSUE TITLE
pull-to-refresh crash

### ISSUE THREAD

**Issue by vdende** [telerik/nativescript-ui-samples#62]
When I run the project in an ios emulator and try the pull-to-refresh, the app crashes. Error on the console:

`Feb 15 16:45:55 juliett sdk[3879]: file:///app/listview/pull-to-refresh/pts-view-model.js:21:38: JS ERROR TypeError: listView.didRefreshOnPull is not a function. (In 'listView.didRefreshOnPull()', 'listView.didRefreshOnPull' is undefined)`

`Feb 15 16:45:55 juliett com.apple.CoreSimulator.SimDevice.C07913C8-EC0D-473F-A862-2F13B8584241.launchd_sim[3811] (UIKitApplication:org.nativescript.sdk[0xfe45][3879]): Service exited due to signal: Segmentation fault: 11`

My tns version is 1.5.2.

**Comment by ginev** [comment]
Hello @vdende ,

Please make sure you transpile the .ts files on your machine. The issue is related to the fact that the .ts files contain the right code, but the .js files on GitHub are not up-to-date. We will remove the .js filed but for now the solution is to transpile the .ts files on your machine before running the app.

**Comment by vdende** [comment]
Hi @ginev,
I'm new to nativescript and also to typescript (I rather use JavaScript). How can I transpile the .ts files?

**Comment by ginev** [comment]
@vdende ,

you can simply open the `pts-view-model.js` file and change the `listView.didRefreshOnPull` to ` listView.notifyPullToRefreshFinished();` as an easier solution.

Otherwise, transpiling TypeScript to JavaScript is done via the `typescript` NPM plugin available here:
https://www.npmjs.com/package/typescript

You can also use Visual Studio Code for that purpose:

https://code.visualstudio.com/Docs/editor/setup

Let me know in case of further questions.
