### ISSUE TITLE
How to set side drawer width?

### ISSUE THREAD

**Issue by jaysson** [telerik/nativescript-ui-samples#63]
Examples don't seem to have it. I want the side drawer width to be more than what it is by default. How to do that?

**Comment by ginev** [comment]
@jaysson , 
you can use the `drawerContentSize` property to adjust the size: http://docs.telerik.com/devtools/nativescript-ui/ApiRef/classes/_sidedrawer_.radsidedrawer.html#drawercontentsize

**Comment by anodal88** [comment]
@ginev the url is not available

**Comment by ginev** [comment]
@anodal88 here it is: http://docs.telerik.com/devtools/nativescript-ui/Api/classes/radsidedrawer.html#drawercontentsize

**Comment by anodal88** [comment]
@ginev thanks for the link.
Do you know how to change this property "drawercontentsize" programmatically ?
Because i have implemented the same drawer to show differents menues from differents   locations, but some times i need that the drawer's change  your size automaticaly, i already tried with the docuentation of telerik but it does not work.

thanks

**Comment by anodal88** [comment]
@ginev The new value for drawercontentsize is setted but in the view you don't never  see the change.

**Comment by arma7x** [comment]
@anodal88 use this drawerSize instead of drawerContentSize
