### ISSUE TITLE
using drawer element with Angular2

### ISSUE THREAD

**Issue by episodeyang** [telerik/nativescript-ui-samples#71]
Hi, 

What is the syntax for using the drawer component with Angular2? In the xml it is used as 

``` xml
<Drawer:RadSideDrawer>
  <Drawer:RadSideDrawer.mainContent>
    <StackLayout>
      <Label text="Test"></Label>
    </StackLayout>
  </Drawer:RadSideDrawer.mainContent>
  <Drawer:RadSideDrawer.drawerContent>
    <StackLayout class="container">
      <Label text="Drawer Test"></Label>
    </StackLayout>
  </Drawer:RadSideDrawer.drawerContent>
</Drawer:RadSideDrawer>
```

**Comment by ginev** [comment]
Hello @episodeyang ,

There's currently no option for using the drawer with Angular 2 but support is coming soon.

**Comment by pratyushsharma** [comment]
Any updates?

**Comment by ngydat** [comment]
any news about the use of this plugin with Angular 2 ??

**Comment by ginev** [comment]
@ngydat plans are to be ready by the end of April.

**Comment by ngydat** [comment]
I found out about this little [tutorial](http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/getting-started#telerik-ui-for-nativescript-with-angular-20-getting-started) on how to use the plugin with Angular 2 but I think there is something missing : in the page a snippet is mentioned but I don't see anything below the text

**Comment by nestor94** [comment]
Check this: https://github.com/telerik/nativescript-ui-samples-angular

**Comment by ngydat** [comment]
@nestor94  I have a little issue though : for the [sidedrawer](https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/app/sidedrawer/getting-started/getting-started.component.ts), there is this line :

`import {RadSideDrawerComponent, SideDrawerType, MainTemplateDirective, DrawerTemplateDirective} from "nativescript-telerik-ui-pro/sidedrawer/angular/side-drawer-directives";`

But the Typescript compiler doesn't recognise it because it cannot find the module (there's only a javascript file in the folder and I think that's the problem)

**Comment by nestor94** [comment]
@ngydat I have the same issue,I think this is  because Angular 2 RC, we have to wait.

**Comment by aandino-dev** [comment]
I have tried with template that generate `tns create my-app --ng` but doesn't work. @nestor94  I bypass that error changing the tsconfig.json like the sample. 
Here the code **tsconfig.json** : 
`{
    "version": "1.8.10",
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": false,
        "watch": false,
        "noLib": false,
        "preserveConstEnums": true,
        "emitDecoratorMetadata": true,
        "suppressImplicitAnyIndexErrors": true,
        "noImplicitUseStrict": true,
        "experimentalDecorators": true
    },
    "filesGlob": [
        "./**/*.ts",
        "!./tns_modules/**/*.ts",
        "./../node_modules/tns-core-modules/**/*.ts"
    ],
    "exclude": [
        "node_modules",
        "platforms"
    ]
}`


There a difference between (sample) `import {Component, ElementRef, ViewChild, Inject} from "angular2/core";` and (mine like ng default template) `import {Component, ElementRef, ViewChild, Inject} from "@angular/core";`

Now my error is:
`
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Failed to find module: "angular2/core", relative to: /app/tns_modules/
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4612)
at android.app.ActivityThread.access$1600(ActivityThread.java:169)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1337)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5476)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
at dalvik.system.NativeStart.main(Native Method)
Caused by: com.tns.NativeScriptException: Failed to find module: "angular2/core", relative to: /app/tns_modules/
at com.tns.Module.resolvePathHelper(Module.java:220)
at com.tns.Module.resolvePath(Module.java:60)
at com.tns.Runtime.runModule(Native Method)
at com.tns.Runtime.runModule(Runtime.java:241)
at com.tns.Runtime.run(Runtime.java:235)
at com.tns.RuntimeHelper.initRuntime(RuntimeHelper.java:129)
at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:13)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4609)
... 10 more
`

**Comment by eleddie** [comment]
I'm not able to implement the side drawer with angular2 final release... Any help?
I do this:
`@ViewChild(RadSideDrawerComponent)`
`public drawerComponent: RadSideDrawerComponent;`
`private drawer: SideDrawerType;`

then 
`ngAfterViewInit() {`
`this.drawer = this.drawerComponent.sideDrawer;`
`this._changeDetectionRef.detectChanges();`
`}`

but I get `TypeError: Cannot read property 'sideDrawer' of undefined`

I have imported the directives en in the ngModule and the Side drawer component in my component but still don't get it to work.

**Comment by vhontar** [comment]
Hi, i have the error  'Cannot read property 'sideDrawer' of undefined'. 
ORIGINAL STACKTRACE:
`JS: TypeError: Cannot read property 'sideDrawer' of undefined                                                                                        
JS:     at SideDrawerComponent.ngAfterViewInit (/data/data/com.yourdomain.appname/files/app/app/frameworks/oms/components/side-drawer/side-drawer.com
ponent.js:12:43)                                                                                                                                     
JS:     at DebugAppView._View_HomeComponent0.detectChangesInternal (/ComponentsModule/HomeComponent/component.ngfactory.js:57:78)                    
JS:     at DebugAppView.AppView.detectChanges (/data/data/com.yourdomain.appname/files/app/tns_modules/@angular/core/bundles/core.umd.js:9197:18)    
JS:     at DebugAppView.detectChanges (/data/data/com.yourdomain.appname/files/app/tns_modules/@angular/core/bundles/core.umd.js:9302:48)            
JS:     at DebugAppView.AppView.detectViewChildrenChanges (/data/data/com.yourdomain.appname/files/app/tns_modules/@angular/core/bundles/core.umd.js:
9223:23)                                                                                                                                             
JS:     at DebugAppView._View_HomeComponent_Host0.detectChangesInternal (/ComponentsModule/HomeComponent/host.ngfactory.js:32:8)                     
JS:     at DebugAppView.AppView.detectChanges (/data/data/com.yourdomain.appname/files/app/tns_modules/@angular/core/bundles/core.umd.js:9197:18)    
JS:     at DebugAppView.detectChanges (/data/data/com.yourdomain.appname/files/app/tns_modules/@angular/core/bundles/core.umd.js:9302:48)            
JS:     at DebugAppView.AppView.detectContentChildrenChanges (/data/data/com.yourdomain.appname/files/app/tns_modules/@angular/core/bundles/core.umd.
js:9215:23)                                                                                                                                          
JS:     at DebugAppView._View_AppComponent0.detectChangesInternal (/NativeModule/AppComponent/component.ngfactory.js:109:8)                          
JS: ERROR CONTEXT:                                                                                                                                   
JS: [object Object]                                                                                                                                  
JS: Error: Error in /data/data/com.yourdomain.appname/files/app/app/frameworks/oms/components/home/home.component.tns.html:1:1 caused by: Cannot read
 property 'sideDrawer' of undefined `

MyComponent:
`import { ViewChild, ChangeDetectorRef } from '@angular/core';
import { RadSideDrawerComponent, SideDrawerType } from 'nativescript-telerik-ui/sidedrawer/angular';
import { Page } from 'ui/page';

 @Component({
    moduleId: module.id,
    selector: 'side-drawer',
    templateUrl: 'side-drawer.component.html',
    styleUrls: ['side-drawer.component.css']
})
export class SideDrawerComponent {

    @ViewChild(RadSideDrawerComponent) public drawerComponent: RadSideDrawerComponent;
    private drawer: SideDrawerType;

    constructor(private page: Page, private _changeDetectionRef: ChangeDetectorRef) {
    }

    ngAfterViewInit() {
        this.drawer = this.drawerComponent.sideDrawer;
        this._changeDetectionRef.detectChanges();
    }

    public openDrawer() {
        this.drawer.showDrawer();
    }
}`

Template: 
`<RadSideDrawer exampleTitle toggleNavButton>
    <StackLayout tkDrawerContent class="sideStackLayout">
        <StackLayout class="sideTitleStackLayout">
            <Label text="Navigation Menu"></Label>
        </StackLayout>
        <StackLayout class="sideStackLayout">
            <Label text="Primary" class="sideLabel sideLightGrayLabel"></Label>
            <Label text="Social" class="sideLabel"></Label>
            <Label text="Promotions" class="sideLabel"></Label>
            <Label text="Labels" class="sideLabel sideLightGrayLabel"></Label>
            <Label text="Important" class="sideLabel"></Label>
            <Label text="Starred" class="sideLabel"></Label>
            <Label text="Sent Mail" class="sideLabel"></Label>
            <Label text="Drafts" class="sideLabel"></Label>
        </StackLayout>
    </StackLayout>
    <StackLayout tkMainContent>
        <Label [text]="mainContentText" textWrap="true" class="drawerContentText"></Label>
        <Button text="OPEN DRAWER" (tap)=openDrawer()></Button>
    </StackLayout>
</RadSideDrawer>`

And in another component i include this my component with RadSideDrawer:
`<side-drawer></side-drawer>`

Any idea?

**Comment by eleddie** [comment]
@vhontar Did you include it in the module?

**Comment by vhontar** [comment]
@eleddie Yes. 
`import { SIDEDRAWER_DIRECTIVES } from 'nativescript-telerik-ui/sidedrawer/angular';`,
`  declarations: [
    AppComponent,
    SIDEDRAWER_DIRECTIVES
  ],`

**Comment by eleddie** [comment]
Try removing and adding back again the platforms

**Comment by vhontar** [comment]
https://github.com/RichardSilveira/angular2-seed-advanced/tree/master/nativescript/app/nativescript.components/homemobile

worker version for me.

**Comment by abhishekit29** [comment]
@vhontar  put a `/`  after `angular` in `import { SIDEDRAWER_DIRECTIVES } from 'nativescript-telerik-ui/sidedrawer/angular';`

**Comment by haschu** [comment]
Same problem here. @vhontar Your link is down, could you please share your working example here?

**Comment by ginev** [comment]
This issue was moved to telerik/nativescript-ui-feedback#122
