### ISSUE TITLE
SideDrawer - example for real apps

### ISSUE THREAD

**Issue by vyscond** [telerik/nativescript-ui-samples#78]
Hi! I notice that the example provided for sidedrawer is not really useful since there is no clue inside of the code how to use it to load custom layouts or as you guys named it "Pages". I think that this is the main goal of using this kind of UI design, right?

Would be really nice see some real actions like manipulating [custom components](https://docs.nativescript.org/ui/ui-with-xml#custom-components)? I don't if this is the best way to inject/switch through "partial" Pages :/

**Comment by ginev** [comment]
Hello @vyscond ,

Currently you can place a RadSideDrawer in your page and provide content by using `mainContent` and `drawerContent`. Pages are usually the root views that you can navigate to throughout your application. Each page can contain any components you like.

Can you please be a bit more specific and let us know what your exact scenario is so that we can help?

**Comment by mn-martin** [comment]
I think I have the same issue as @vyscond does.

Here's an example:

__main.xml__
```xml
<dpg:DrawerPage xmlns="http://schemas.nativescript.org/tns.xsd"
                xmlns:dpg="nativescript-telerik-ui/sidedrawer/drawerpage"
                xmlns:navbar="~/components/navbar"
                xmlns:side-drawer="~/components/side-drawer"
                navigatingTo="navigatingTo"
                class="page drawerPage">

    <dpg.actionBar>
        <navbar:navbar/>
    </dpg.actionBar>

    <side-drawer:side-drawer/>

    <ScrollView class="mainContent">
        <StackLayout class="p-20">
            <Label text="Example" class="h1 text-center"/>
        </StackLayout>
    </ScrollView>
</dpg:DrawerPage>
```

__side-drawer.xml__
```xml
<dpg:DrawerPage.sideDrawer xmlns:dpg="nativescript-telerik-ui/sidedrawer/drawerpage"
                           xmlns:drawer="nativescript-telerik-ui/sidedrawer">

    <drawer:RadSideDrawer id="sideDrawer">
        <drawer:RadSideDrawer.drawerContent>
            <ScrollView>
                <StackLayout class="drawerContent">
                    <StackLayout class="drawerMenuContent">
                        <Label text="Example" class="drawerSectionItem"/>
                    </StackLayout>
                </StackLayout>
            </ScrollView>
        </drawer:RadSideDrawer.drawerContent>
    </drawer:RadSideDrawer>
</dpg:DrawerPage.sideDrawer>
```

This will throw me the following error message:

`Error: Building UI from XML. @file:///app/pages/main/main.xml:12:5 > Building UI from XML. @file:///app/components/side-drawer/side-drawer.xml:1:1 > Cannot read property 'exports' of undefined File: "file:///data/data/org.example.app/files/app/tns_modules/tns-core-modules/ui/builder/builder.js, line: 175, column: 20`

(I'm using package.json files to point to the .xml files, which works fine for `<navbar:navbar/>` so I guess that's not the issue)

That way it seems to be pretty unusable to me right now. I don't consider it to be acceptable repeating the side drawer nav markup in each and every xml file. Generally the custom components documentation needs to be improved thought. I'm feeling completely lost at that point and it's such an important topic if you event want to consider using the typescript template.

And I've even had a look at [a pretty comprehensive blog article.](https://moduscreate.com/custom-components-in-nativescript/)
(Unfortunately I couldn't manage to get the arguments thing to work and it of course didn't cover the SideDrawer – Guess it's maybe a bit outdated as well?)

```bash
$ tns --version
2.5.2
```

```json
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.example.app",
    "tns-ios": {
      "version": "2.5.0"
    },
    "tns-android": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "nativescript-barcodescanner": "^2.4.0",
    "nativescript-bluetooth": "^1.1.4",
    "nativescript-loading-indicator": "^2.2.2",
    "nativescript-orientation": "^1.5.4",
    "nativescript-telerik-ui": "^1.6.1",
    "nativescript-theme-core": "~1.0.2",
    "tns-core-modules": "^2.5.1"
  },
  "devDependencies": {
    "babel-traverse": "6.23.1",
    "babel-types": "6.23.0",
    "babylon": "6.15.0",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-sass": "^0.4.2",
    "nativescript-dev-typescript": "~0.3.5",
    "tns-platform-declarations": "^2.5.0",
    "typescript": "~2.1.0"
  }
}
```

**Comment by mn-martin** [comment]
I just managed to get it working putting only the following partial into my __side-drawer.xml__

```xml
<ScrollView>
    <StackLayout class="drawerContent">
        <StackLayout class="drawerMenuContent">
            <Label text="Example" class="drawerSectionItem"/>
        </StackLayout>
    </StackLayout>
</ScrollView>
```

But still that will lead into a lot of code duplication. Isn't there a better way of doing these things? Maybe some master-partial pattern? Includes? Anything to write beautiful DRY code? Please allow us to or consider creating some options for us typescript without angular users. 👍

**Comment by ginev** [comment]
@mn-martin thanks for the feedback.

Can I first as you to make sure any future issues regarding UI for NativeScript are posted here:
https://github.com/telerik/nativescript-ui-feedback?

You've got it right about the side-drawer.xml partial. In this way, you can define the drawer content in a separate XML file and reuse it throughout all pages were RadSideDrawer is integrated.

As of now, there is no way to make each page automatically containt a RadSideDrawer. You will have to integrate it in each page where needed. In other words, consider the RadSideDrawer component as something you put on a page, not vice-versa.

Can you elaborate a bit further on the custom components documentation limitations you have in mind? Thanks!

**Comment by mn-martin** [comment]
@ginev [https://docs.nativescript.org/ui/basics#custom-components](https://docs.nativescript.org/ui/basics#custom-components) This is the only official documentation about the topic that I've found. It's not showing how to pass arguments to the custom components for example. It's not telling anything about event behavior within components. What to consider using contexts, sharing context between components etc. It must be a huge topic if all the amazing features are covered. Right now in my opinion it's just scratching the surface and that's what could and should be improved because it's a really critical topic when going the plain JS / TS route.

{NS} is extremely powerful. I'm really excited about it and am thankful to be able to use it. I'm just trying to say that for me the most important upcoming feature would be improved documentation that goes into much greater detail.

**Comment by ginev** [comment]
@mn-martin, thanks for the feedback! Since this repository is focused on the UI for NativeScript plugin, you may want to share your thoughts on the documentation in the Forums hosted on nativescript.org or using the public github.com/nativescript/nativescript repository.

I can confirm that we plan to invest a lot in documenting how custom components and plugins are built. We will create best practices with examples that will help developers get started in that direction.

**Comment by mn-martin** [comment]
@ginev Thank you, I'm glad to hear that.

**Comment by ginev** [comment]
This issue was moved to telerik/nativescript-ui-feedback#123
