### ISSUE TITLE
Support for LinearAxis.labelTemplate

### ISSUE THREAD

**Issue by Daxito** [telerik/nativescript-ui-samples#81]
We have labelFormat which is great, but sometimes (like in my case) we would like to give some complex format to the labels based on some logic, this would be just to format the label and nothing else, so a converter would be nice to have, something like this (copied from other Telerik products):

 < chart:LinearAxis id="MyTopAxis"
                     verticalLocation="Top"
                     **labelFormat="%1.0f"**>    <-- This is not enough
**<-- What would be very helpful to have -->**
                    < chart:LinearAxis.labelTemplate>
                        < chart:DataTemplate>
                            < TextBlock text="{{$value | Call_Format_Converter_Here()}}" />
                        </ chart:DataTemplate>
                            </ chart:LinearAxis.labelTemplate>
                     </ chart:LinearAxis>

I was checking the docs and couldn't find it, so I think it is missing...

**Comment by Natalia-Hristova** [comment]
Hello @Daxito , 

I'll move this issue in our dedicated GitHub repository for NativeScript UI issues https://github.com/telerik/nativescript-ui-feedback/issues. All issues here will be moved (if they are still valid) and closed because this repository is only for examples.

If you have any feedback, issues or feature requests please log them in [nativescript-ui-feedback](https://github.com/telerik/nativescript-ui-feedback) repository.

Thank you in advance!
