### ISSUE TITLE
iOS Chart incorrect rendering, Android is ok.

### ISSUE THREAD

**Issue by Daxito** [telerik/nativescript-ui-samples#82]
iOS renders an unexpected chart, Android is ok.
I have attached this sample app, the chart I am expecting is this (Android):

![android_chart](https://cloud.githubusercontent.com/assets/16787057/14063452/7897b324-f397-11e5-894f-0d11c45fa299.png)

When I run the app in iOS, I get this, which is not what I am expecting, I am expecting the same chart Android renders:

![ios_chart](https://cloud.githubusercontent.com/assets/16787057/14063456/97bd3134-f397-11e5-9aba-1d54bb9ede51.png)

Please run this attached sample, it contains my special chart, I removed the "platforms" and the "nativescript-telerik-ui" content to reduce file size.

[SampleChart.zip](https://github.com/telerik/nativescript-ui-samples/files/190744/SampleChart.zip)

Am I missing something? I am evaluating the chart control and I want to know the limitations of it.

**Comment by Daxito** [comment]
So any idea? I need to know if iOS is able to render this chart before I buy it.

Thank you!

**Comment by karaahmed** [comment]
Hi Daxito,
The issue you pointed above really exists. There is a workaround that I could suggest at least for now, but I'll include a fix with the very next official release. Do you know that yesterday we officially released the NativeScript UI bundle?
So, you could just reverse the category & value properties for iOS only as follows:
```
 <chart:LineSeries strokeThickness="5" seriesName="hrsService" items="{{ items }}" 
    android:categoryProperty="Category" android:valueProperty="Amount" 
    ios:categoryProperty="Amount" ios:valueProperty="Category"/>

```
With next version you will need to set your horizontal & vertical axis as properties of series in order the appropriate category axis to be found and bound to the series. Currently in iOS version the series expects the category axis to be the horizontal one and that's why if you set the vertical one as categorical the chart engine is not able to decide if it should be used as category axis of the series. 

Please, let me know if this fix works for you and is acceptable, at least for now.

**Comment by Daxito** [comment]
Yes, I am aware of these official release.
Well, it does not render the same chart exactly, I think I will wait for the final fix.
Thanks

**Comment by karaahmed** [comment]
Could you send me screenshots and point what is different. iOS & Android charts in their native part are different, so small visual difference are expecting, but the chart configuration and series should be the same.

**Comment by Daxito** [comment]
The labels at the left side, should be outside of the chart, this chart is very special, so the label inside is not an option. Let me know if you need more info.

![screen shot 2016-04-04 at 12 59 28 am](https://cloud.githubusercontent.com/assets/16787057/14239381/af2b151a-fa00-11e5-9ec9-43b0c79328c0.png)

**Comment by karaahmed** [comment]
You are right, but this is customizable. Just set _labelLayoutMode_ to **Outer** as follows;
` <chart:CategoricalAxis horizontalLocation="Left" labelTextColor="black" labelSize="20" lineThickness="2" lineColor="black" labelLayoutMode="Outer"/>`

**Comment by Daxito** [comment]
Yes, it worked! I don't see this in the docs but it works.
Is this a good place for a question about why this chart says "Trial" even though I installed the "Pro" version already paid?

**Comment by karaahmed** [comment]
You are right, it is not explicitly documented, since it is one of the recently added features, but will add this additional options to documentation.
So, I can guess that you didn't remove your **lib/iOS** folder from the root after adding **Pro** plugin and the trial version of TelerikUI.framework left and deployed on device instead of the new Pro version. Could you please delete lib/iOS folder and prepare your iOS project again.

**Comment by Daxito** [comment]
Yes you were correct! Thank you, I think this should be part of the instructions when installing the pro version.

**Comment by karaahmed** [comment]
Yes, this is known issue and we should warn for this in instructions.
I'm glad to hear that everything is OK now. 
Let me know if you have any issues.
