### ISSUE TITLE
Calendar - how to insert icons in a day cell?

### ISSUE THREAD

**Issue by MiroValchev** [telerik/nativescript-ui-samples#84]
Hi guys!

It's great that there are now options to style a calendar cell - 
http://docs.telerik.com/devtools/nativescript-ui/Controls/Calendar/Styling/month-view-styling
My question is how can I add icons to a given cell. Also, is there a way to provide my own template for calendar cells?

**Comment by karaahmed** [comment]
Hi Miro,
currently feature for custom shapes for events in calendar is not supported, but it is planned for next release. I think it should be ready soon.

**Comment by MiroValchev** [comment]
Hi!

Any chance for custom templates soon? Having custom icons for events would still be great :) Hope the new release will be soon :)

Cheers!

**Comment by Natalia-Hristova** [comment]
Hello @MiroValchev , 

I'll move this issue in our dedicated GitHub repository for NativeScript UI issues https://github.com/telerik/nativescript-ui-feedback/issues. All issues here will be moved (if they are still valid) and closed because this repository is only for examples.

If you have any feedback, issues or feature requests please log them in [nativescript-ui-feedback](https://github.com/telerik/nativescript-ui-feedback) repository.

Thank you in advance!
